### ISSUE TITLE
Emacs hanging when pointer after [something]

### ISSUE THREAD

**Issue by wdenton** [Fuco1/smartparens#868]
## Expected behavior

Emacs works in its usual smooth way.

## Actual behavior

System becomes unresponsive and Emacs chews up 100% of a CPU forever, until a lot of C-g keystrokes are hit.

## Steps to reproduce the problem

In Org, start a clocktable log like this, and use C-e to move to the end of the CLOCK line. My system hangs.

````
:LOGBOOK:
CLOCK: [2018-03-05 Mon 09:40]
:END:
````

Also just a date works:

````
[2018-03-05 Mon]
````

## Profiler report 

Here's a profiler report (done with M-x profiler-start, moving to the end of the line, waiting a bit, then hitting C-g a lot, then M-x profiler-report):

````
- timer-event-handler                                     208,671,212  95%
 - apply                                                  207,879,212  95%
  - sp-show--pair-function                                207,582,008  94%
   - #<compiled 0x1f8cfbd>                                207,396,904  94%
    - sp-get-thing                                        207,396,904  94%
     - sp-get-sexp                                        207,283,660  94%
      - sp-get-expression                                 207,283,660  94%
       - sp--find-next-stringlike-delimiter               192,437,884  88%
        + sp--search-backward-in-context                  111,950,048  51%
        + sp--looking-back-p                               54,012,600  24%
        + sp--skip-match-p                                  8,135,588   3%
          match-string-no-properties                        1,572,096   0%
          make-byte-code                                        3,366   0%
          vconcat                                               1,122   0%
       + sp--get-allowed-regexp                                20,768   0%
       + sp--get-stringlike-regexp                             12,496   0%
         sp--search-backward-in-context                         1,056   0%
     + sp-skip-backward-to-symbol                              87,284   0%
     + sp--get-closing-regexp                                  17,600   0%
     + sp--get-allowed-pair-list                                6,248   0%
     + sp-point-in-empty-string                                 1,056   0%
   + sp--get-opening-regexp                                    67,116   0%
   + sp--get-closing-regexp                                    45,584   0%
   + sp--get-stringlike-regexp                                 35,464   0%
   + sp--get-allowed-pair-list                                 18,796   0%
     sp--looking-back                                           7,584   0%
     sp--looking-at                                             4,352   0%

````

## Environment & version information

- `smartparens` version: 20180304.849
- Active major-mode: Org
- Emacs version (`M-x emacs-version`): 27.0.50 (compiled from source fresh today)
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: none
- OS: Linux / Ubuntu

**Comment by Fuco1** [comment]
Something similar happened to me yesterday, I wasn't sure if it's my local config or not.  So yea, thanks for confirming my nightmare, I broke something (again :/)!

Thanks for the profiler report that should be super helpful!

**Comment by ncaq** [comment]
I do not think this bug is limited to org-mode.

I confirmed equal bug on haskell-mode.

I report too.

# Profiler report

~~~
- timer-event-handler                       2223  59%
 - apply                                    2223  59%
  - sp-show--pair-function                  2207  59%
   - #<compiled 0xf9afeb>                   2189  58%
    - sp-get-thing                          2175  58%
     - sp-get-sexp                          2166  58%
      - sp-get-expression                   2165  58%
       - sp--find-next-stringlike-delimiter 2127  57%
        - sp--search-backward-in-context    1725  46%
         - sp--get-context                  1538  41%
          - sp-point-in-string              1402  37%
           - sp--syntax-ppss                1358  36%
              syntax-ppss                   1304  35%
          - sp-point-in-comment               66   1%
             syntax-after                     12   0%
         - sp--search-backward-regexp        148   3%
          - sp--looking-back                  77   2%
             #<compiled 0x224ee05>             2   0%
        - sp--looking-back-p                 163   4%
         - sp--looking-back                   69   1%
            #<compiled 0x2981555>              7   0%
           #<compiled 0x2a65367>               2   0%
        - sp-get-pair                         48   1%
         - sp--get-pair-definition            42   1%
            sp--get-pair                       3   0%
        - sp--skip-match-p                    45   1%
         - sp-haskell-skip-apostrophe         16   0%
            syntax-after                       8   0%
            syntax-class                       1   0%
           #<compiled 0x2900f93>               4   0%
        + sp--search-forward-in-context       20   0%
          #<compiled 0x2860e49>                3   0%
          match-string-no-properties           2   0%
       + sp-get-paired-expression              2   0%
       + sp--search-backward-in-context        1   0%
       + sp--get-stringlike-regexp             1   0%
     + sp-skip-backward-to-symbol              5   0%
     + sp-skip-forward-to-symbol               2   0%
     + sp--get-allowed-pair-list               2   0%
    + sp-show--pair-echo-match                14   0%
   + sp--get-allowed-pair-list                 7   0%
   + sp--get-closing-regexp                    5   0%
   + sp--get-opening-regexp                    4   0%
     sp--looking-back                          2   0%
  + #<compiled 0x206f95>                      14   0%
~~~

# Environment & version information

* smartparens version: 20180304.849
* Active major-mode: haskell
* Emacs version (M-x emacs-version): 25.3.1
* Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
* OS: Linux / Gentoo

**Comment by Fuco1** [comment]
@ncaq Thanks for the report.

I can't quite remember any such changes that should cause this but it seems to be pretty serious and somehow related to string lookup (which is so messy you don't even want to know).

I don't think I can get to this sooner than on the weekend so for now a "non-solution" would be to reverting to the stable release (which I hope does not have this issue :D)

**Comment by nmk** [comment]
I can confirm that this is at least partially major mode dependent. In ruby-mode I cannot reproduce this. In haskell-mode it happens _sometimes_. I have not been able to recognize a pattern when and why it happens.

**Comment by Fuco1** [comment]
This seems to be related to the changes I've done last weekend.  If you roll back to anything older than a week can someone confirm it is not happening?

I think this commit might be the cause dac80d1 so roll back before that.

**Comment by svenpanne** [comment]
I don't know how to roll back single packages in spacemacs, so I just locally reverted the change made to `smartparens.el` in dac80d1ec567ebc8ff646b793e9eb90d70d4100f, and this fixes the problem in my example! 😄 Whatever that commit does, it should probably be reverted quickly for now: Having to kill Emacs frequently is a showstopper for this minor mode IMHO.

**Comment by CarstenKoenig** [comment]
I've got this problem too - spacemacs/haskell/intero (luckily reverting back to march first solves the issue)

I can 100% reproduce in this scenario by just starting a `(` (it will add the closing `)` and hang at once - I have to hit CTRL-G like an idiot and try to navigate away from the spot - after if I hit del/backspace fast enough I can get rid of the parens)

here is my profiling report:

```
- timer-event-handler                                            3830  91%
 - apply                                                         3830  91%
  - sp-show--pair-function                                       3642  87%
   - #<compiled 0x2a59a17>                                       3632  87%
    - sp-get-thing                                               3632  87%
     - sp-get-sexp                                               3628  86%
      - sp-get-expression                                        3624  86%
       - sp--find-next-stringlike-delimiter                      3600  86%
        - sp--search-backward-in-context                         3368  80%
         - sp--get-context                                       2824  67%
          - sp-point-in-string                                   2688  64%
           - sp--syntax-ppss                                     2668  63%
              syntax-ppss                                        2628  62%
 ```

**Comment by Fuco1** [comment]
Thanks everyone for the reports/confirmations, I will roll back when I get home ASAP and try to fix it either today or on the weekend

**Comment by Fuco1** [comment]
@CarstenKoenig what emacs version are you using?  I'm trying haskell mode but can't reproduce this, neither with org mode.  Very odd.

**Comment by Fuco1** [comment]
I've pushed a revert for the mentioned commit to master so if someone can jump on that (ideally with a restarted emacs) and confirm that's the problem it will be super helpful :)

**Comment by CarstenKoenig** [comment]
I'm using  0.200.13@25.3.2 (spacemacs) on GNU Emacs 25.3.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)

so it's really hard to say what exactly causes it (intero had updates as well - and deactivating smartparens mode does not solve the issue - but rolling back to one of the upgrades did - sorry would love to tell you more but the profiler brought me here)

**Comment by svenpanne** [comment]
FYI: I've just updated my spacemacs packages, which pulled in smartparens-20180308.1042 (including the revert 3181747d9b84ed44b95fa95855609b624ce83d9b), and my haskell-mode is happy again now. My guess is that other spacemacs users will be up and running again, too, after "Update Packages".

Thanks for the quick fix!

**Comment by CarstenKoenig** [comment]
same here - thank you!

**Comment by Fuco1** [comment]
My suspicion is that there is an infinite loop caused by something related to `sp--get-context`---in some weird cases it might probably happen that `syntax-ppss` returns garbage and the retry logic there goes haywire.

I still can't repro this on my own setup so maybe I'll try to grab spacemacs... but OP said they use vanilla emacs so I should be able to get this but to surface :D Oh well...

**Comment by algking** [comment]
Same problem in php-mode, I can reproduce this in php-mode.

1. `xxx()`
2.`xxx()[]`
3. `xxx()]`
If delete the `]` ,then emacs will block

```
Debugger entered--entering a function:
* #f(compiled-function () #<bytecode 0x5ab0dbe1>)()
  syntax-ppss(52461)
  sp--syntax-ppss(nil)
  sp-point-in-string(nil)
  sp-point-in-string-or-comment()
  sp-get-paired-expression(t)
  sp-get-expression(t)
  sp-get-sexp(t)
  sp-get-thing(:back)
  #f(compiled-function (match &optional back) #<bytecode 0x40b7fa35>)(#("]" 0 1 (fontified t)) :back)
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])
  recursive-edit()
  debug(lambda)
* #f(compiled-function () #<bytecode 0x593ea969>)()
  syntax-ppss(57679)
  sp--syntax-ppss(nil)
  sp-point-in-string(nil)
  sp-point-in-string-or-comment()
  sp-get-paired-expression(t)
  sp-get-expression(t)
  sp-get-sexp(t)
  sp-get-thing(:back)
  #f(compiled-function (match &optional back) #<bytecode 0x40b7fa35>)(#("]" 0 1 (fontified t)) :back)
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])
  recursive-edit()
  debug(error (quit))
  re-search-backward("\\(?:^\\s-*function\\s-+&?\\s-*\\(\\(\\sw\\|\\s_\\)+\\)\\s-*\\)\\s(" nil move 1)
  beginning-of-defun-raw(nil)
  beginning-of-defun()
  c-beginning-of-syntax()
  syntax-ppss(59856)
  sp--syntax-ppss(nil)
  sp-point-in-string(nil)
  sp-point-in-string-or-comment()
  sp-get-paired-expression(t)
  sp-get-expression(t)
  sp-get-sexp(t)
  sp-get-thing(:back)
  #f(compiled-function (match &optional back) #<bytecode 0x40f978f1>)(#("]" 0 1 (fontified t)) :back)
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])

```
```

**Comment by Fuco1** [comment]
@algking I'm using php mode daily and have not experienced this.  Do you have latest smartparens version or the stable release?

**Comment by algking** [comment]
@Fuco1 I use the 20180325 version in melpa. emacs 26.1
